/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/9.2.1/userguide/multi_project_builds.html in the Gradle documentation.
 * This project uses @Incubating APIs which are subject to change.
 */

rootProject.name = "workshop"

include(
    ":task-1",
    ":task-2",
    ":task-3",
    ":task-4",
    ":task-5",
    ":task-6",
    ":task-7",
    ":task-8",
    ":task-9",
)